export const GET_SERVICES = 'GET_SERVICES';
export const GET_COVERAGE = 'GET_COVERAGE';
export const GET_GALLERY = 'GET_GALLERY';
export const GET_ORDERS = 'GET_ORDERS';
export const CANCEL_ORDER = 'CANCEL_ORDER';

export const GET_EXPERT_OPEN_ORDERS = 'GET_EXPERT_OPEN_ORDERS';
export const GET_EXPERT_ACTIVE_ORDERS = 'GET_EXPERT_ACTIVE_ORDERS';
export const GET_EXPERT_HISTORY_ORDERS = 'GET_EXPERT_HISTORY_ORDERS';
